// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_app.tsx'
import * as $$0 from './islands/AddToCartButton/vtex.tsx'
import * as $$1 from './islands/BuyTogether.tsx'
import * as $$2 from './islands/Header/Buttons.tsx'
import * as $$3 from './islands/Header/Cart/vtex.tsx'
import * as $$4 from './islands/Header/HeaderJS.tsx'
import * as $$5 from './islands/Header/MainJS.tsx'
import * as $$6 from './islands/Header/Search.tsx'
import * as $$7 from './islands/HeaderButton.tsx'
import * as $$8 from './islands/HeaderButtons.tsx'
import * as $$9 from './islands/HeaderModals.tsx'
import * as $$10 from './islands/HeaderSearchbar.tsx'
import * as $$11 from './islands/MenuMobile.tsx'
import * as $$12 from './islands/MicroHeaderSetup.tsx'
import * as $$13 from './islands/Navbar.tsx'
import * as $$14 from './islands/Newsletter.tsx'
import * as $$15 from './islands/NextButtonJS.tsx'
import * as $$16 from './islands/OutOfStock.tsx'
import * as $$17 from './islands/PrevButtonJS.tsx'
import * as $$18 from './islands/ProductBuyFixed.tsx'
import * as $$19 from './islands/ProductCardModal.tsx'
import * as $$20 from './islands/ProductImageZoom.tsx'
import * as $$21 from './islands/ProductQuantityCartAndShipping.tsx'
import * as $$22 from './islands/ProductQuantitySelector.tsx'
import * as $$23 from './islands/ProductSpecificationsJs.tsx'
import * as $$24 from './islands/PureModal.tsx'
import * as $$25 from './islands/QuantitySelector.tsx'
import * as $$26 from './islands/QuemSomos/VideoModal.tsx'
import * as $$27 from './islands/QuemSomos/VideoModalButton.tsx'
import * as $$28 from './islands/SearchControls.tsx'
import * as $$29 from './islands/SearchResultJS.tsx'
import * as $$30 from './islands/ShippingSimulation.tsx'
import * as $$31 from './islands/SliderJS.tsx'
import * as $$32 from './islands/SliderJsNew.tsx'
import * as $$33 from './islands/WishlistButton.tsx'

const manifest = {
	routes: {
		'./routes/_app.tsx': $0,
	},
	islands: {
		'./islands/AddToCartButton/vtex.tsx': $$0,
		'./islands/BuyTogether.tsx': $$1,
		'./islands/Header/Buttons.tsx': $$2,
		'./islands/Header/Cart/vtex.tsx': $$3,
		'./islands/Header/HeaderJS.tsx': $$4,
		'./islands/Header/MainJS.tsx': $$5,
		'./islands/Header/Search.tsx': $$6,
		'./islands/HeaderButton.tsx': $$7,
		'./islands/HeaderButtons.tsx': $$8,
		'./islands/HeaderModals.tsx': $$9,
		'./islands/HeaderSearchbar.tsx': $$10,
		'./islands/MenuMobile.tsx': $$11,
		'./islands/MicroHeaderSetup.tsx': $$12,
		'./islands/Navbar.tsx': $$13,
		'./islands/Newsletter.tsx': $$14,
		'./islands/NextButtonJS.tsx': $$15,
		'./islands/OutOfStock.tsx': $$16,
		'./islands/PrevButtonJS.tsx': $$17,
		'./islands/ProductBuyFixed.tsx': $$18,
		'./islands/ProductCardModal.tsx': $$19,
		'./islands/ProductImageZoom.tsx': $$20,
		'./islands/ProductQuantityCartAndShipping.tsx': $$21,
		'./islands/ProductQuantitySelector.tsx': $$22,
		'./islands/ProductSpecificationsJs.tsx': $$23,
		'./islands/PureModal.tsx': $$24,
		'./islands/QuantitySelector.tsx': $$25,
		'./islands/QuemSomos/VideoModal.tsx': $$26,
		'./islands/QuemSomos/VideoModalButton.tsx': $$27,
		'./islands/SearchControls.tsx': $$28,
		'./islands/SearchResultJS.tsx': $$29,
		'./islands/ShippingSimulation.tsx': $$30,
		'./islands/SliderJS.tsx': $$31,
		'./islands/SliderJsNew.tsx': $$32,
		'./islands/WishlistButton.tsx': $$33,
	},
	baseUrl: import.meta.url,
}

export default manifest
