// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from './loaders/url.ts'
import * as $$$1 from './loaders/isMobile.ts'
import * as $$$$$$0 from './sections/Layout/Space.tsx'
import * as $$$$$$1 from './sections/Institutional/Institutional.tsx'
import * as $$$$$$2 from './sections/Institutional/QuemSomos.tsx'
import * as $$$$$$3 from './sections/Social/InstagramPosts.tsx'
import * as $$$$$$4 from './sections/Content/Faq.tsx'
import * as $$$$$$5 from './sections/Content/Logos.tsx'
import * as $$$$$$6 from './sections/Content/Testimonials.tsx'
import * as $$$$$$7 from './sections/Content/Brands.tsx'
import * as $$$$$$8 from './sections/Content/TipsForBusiness.tsx'
import * as $$$$$$9 from './sections/Content/Benefits.tsx'
import * as $$$$$$10 from './sections/Def/Deferred.tsx'
import * as $$$$$$11 from './sections/Links/Shortcuts.tsx'
import * as $$$$$$12 from './sections/Footer/Footer.tsx'
import * as $$$$$$13 from './sections/Theme/Theme.tsx'
import * as $$$$$$14 from './sections/Product/ProductDetails.tsx'
import * as $$$$$$15 from './sections/Product/ProductBuyTogether.tsx'
import * as $$$$$$16 from './sections/Product/BannerShelf.tsx'
import * as $$$$$$17 from './sections/Product/Wishlist.tsx'
import * as $$$$$$18 from './sections/Product/ProductCardModal.tsx'
import * as $$$$$$19 from './sections/Product/ProductShelf.tsx'
import * as $$$$$$20 from './sections/Product/SearchResult.tsx'
import * as $$$$$$21 from './sections/Newsletter/Newsletter.tsx'
import * as $$$$$$22 from './sections/Category/CategoryList.tsx'
import * as $$$$$$23 from './sections/Category/CategoryBanner.tsx'
import * as $$$$$$24 from './sections/Header/Header.tsx'
import * as $$$$$$25 from './sections/Miscellaneous/CookieConsent.tsx'
import * as $$$$$$26 from './sections/Miscellaneous/CampaignTimer.tsx'
import * as $$$$$$27 from './sections/Images/ThreeBanners.tsx'
import * as $$$$$$28 from './sections/Images/TwoBanners.tsx'
import * as $$$$$$29 from './sections/Images/BannerGrid.tsx'
import * as $$$$$$30 from './sections/Images/Banner.tsx'
import * as $$$$$$31 from './sections/Images/ImageGallery.tsx'
import * as $$$$$$32 from './sections/Images/ShoppableBanner.tsx'
import * as $$$$$$33 from './sections/Images/Carousel.tsx'
import * as $$$$$$$$$$$0 from './apps/site.ts'

const manifest = {
	'loaders': {
		'deco-sites/teste1434/loaders/isMobile.ts': $$$1,
		'deco-sites/teste1434/loaders/url.ts': $$$0,
	},
	'sections': {
		'deco-sites/teste1434/sections/Category/CategoryBanner.tsx': $$$$$$23,
		'deco-sites/teste1434/sections/Category/CategoryList.tsx': $$$$$$22,
		'deco-sites/teste1434/sections/Content/Benefits.tsx': $$$$$$9,
		'deco-sites/teste1434/sections/Content/Brands.tsx': $$$$$$7,
		'deco-sites/teste1434/sections/Content/Faq.tsx': $$$$$$4,
		'deco-sites/teste1434/sections/Content/Logos.tsx': $$$$$$5,
		'deco-sites/teste1434/sections/Content/Testimonials.tsx': $$$$$$6,
		'deco-sites/teste1434/sections/Content/TipsForBusiness.tsx': $$$$$$8,
		'deco-sites/teste1434/sections/Def/Deferred.tsx': $$$$$$10,
		'deco-sites/teste1434/sections/Footer/Footer.tsx': $$$$$$12,
		'deco-sites/teste1434/sections/Header/Header.tsx': $$$$$$24,
		'deco-sites/teste1434/sections/Images/Banner.tsx': $$$$$$30,
		'deco-sites/teste1434/sections/Images/BannerGrid.tsx': $$$$$$29,
		'deco-sites/teste1434/sections/Images/Carousel.tsx': $$$$$$33,
		'deco-sites/teste1434/sections/Images/ImageGallery.tsx': $$$$$$31,
		'deco-sites/teste1434/sections/Images/ShoppableBanner.tsx': $$$$$$32,
		'deco-sites/teste1434/sections/Images/ThreeBanners.tsx': $$$$$$27,
		'deco-sites/teste1434/sections/Images/TwoBanners.tsx': $$$$$$28,
		'deco-sites/teste1434/sections/Institutional/Institutional.tsx': $$$$$$1,
		'deco-sites/teste1434/sections/Institutional/QuemSomos.tsx': $$$$$$2,
		'deco-sites/teste1434/sections/Layout/Space.tsx': $$$$$$0,
		'deco-sites/teste1434/sections/Links/Shortcuts.tsx': $$$$$$11,
		'deco-sites/teste1434/sections/Miscellaneous/CampaignTimer.tsx': $$$$$$26,
		'deco-sites/teste1434/sections/Miscellaneous/CookieConsent.tsx': $$$$$$25,
		'deco-sites/teste1434/sections/Newsletter/Newsletter.tsx': $$$$$$21,
		'deco-sites/teste1434/sections/Product/BannerShelf.tsx': $$$$$$16,
		'deco-sites/teste1434/sections/Product/ProductBuyTogether.tsx': $$$$$$15,
		'deco-sites/teste1434/sections/Product/ProductCardModal.tsx': $$$$$$18,
		'deco-sites/teste1434/sections/Product/ProductDetails.tsx': $$$$$$14,
		'deco-sites/teste1434/sections/Product/ProductShelf.tsx': $$$$$$19,
		'deco-sites/teste1434/sections/Product/SearchResult.tsx': $$$$$$20,
		'deco-sites/teste1434/sections/Product/Wishlist.tsx': $$$$$$17,
		'deco-sites/teste1434/sections/Social/InstagramPosts.tsx': $$$$$$3,
		'deco-sites/teste1434/sections/Theme/Theme.tsx': $$$$$$13,
	},
	'apps': {
		'deco-sites/teste1434/apps/site.ts': $$$$$$$$$$$0,
	},
	'name': 'deco-sites/teste1434',
	'baseUrl': import.meta.url,
}

export type Manifest = typeof manifest

export default manifest
